apiVersion: v1/apps
Kind: Deployment
metadata:
  namesapce: expense
  name: backend
  labels:
    project: expense
    tier: api
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: api
      app: backend
  template:
    metadata:
      labels:
        project: expense
        tier: api
        app: backend
    spec:
      container:
      - name: backend
        image: joindevops/backend:v1

---
kind: service
apiVersion: v1
metadata:
  namespace: expense
  name: backend
spec:
  selector:
    project: expense
    tier: api
    app: backend
  port:
    - name: backend-port
      protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port


